

export const DEPARTEMENTS =
    [
        {
            id: 1,
            nom: "Écologie et Environnement",
            faculty_id: 1,
            etablissement_id: 1,
        },
        {
            id: 2,
            nom: "Biologie Cellulaire et Moléculaire",
            faculty_id: 1,
            etablissement_id: 1,
        },
        {
            id: 3,
            nom: "Biologie et Physiologie des Organismes",
            faculty_id: 1,
            etablissement_id: 1,
        },
        {
            id: 4,
            nom: "Palier SNV Licence 2",
            faculty_id: 1,
            etablissement_id: 1,
        },
        {
            id: 5,
            nom: "Chimie Organique",
            faculty_id: 2,
            etablissement_id: 1,
        },
        {
            id: 6,
            nom: "Chimie Physique et Théorique",
            faculty_id: 2,
            etablissement_id: 1,
        },
        {
            id: 7,
            nom: "Chimie Macromoléculaire",
            faculty_id: 2,
            etablissement_id: 1,
        },
        {
            id: 8,
            nom: "Chimie et Physique des Matériaux Inorganique",
            faculty_id: 2,
            etablissement_id: 1,
        },
        {
            id: 9,
            nom: "Géotechnique et hydraulique",
            faculty_id: 3,
            etablissement_id: 1,
        },
        {
            id: 10,
            nom: "Structures et Matériaux",
            faculty_id: 3,
            etablissement_id: 1,
        },
        {
            id: 11,
            nom: "Electronique",
            faculty_id: 4,
            etablissement_id: 1,
        },
        {
            id: 12,
            nom: "Automatique",
            faculty_id: 4,
            etablissement_id: 1,
        },
        {
            id: 13,
            nom: "Electrotechnique",
            faculty_id: 4,
            etablissement_id: 1,
        },
        {
            id: 14,
            nom: "Télécommunication",
            faculty_id: 4,
            etablissement_id: 1,
        },
        {
            id: 15,
            nom: "Géographie et de l’Aménagement du Territoire",
            faculty_id: 5,
            etablissement_id: 1,
        },
        {
            id: 16,
            nom: "Géologie",
            faculty_id: 5,
            etablissement_id: 1,
        },
        {
            id: 17,
            nom: "Géophysique",
            faculty_id: 5,
            etablissement_id: 1,
        },
        {
            id: 18,
            nom: "Systèmes Informatiques",
            faculty_id: 6,
            etablissement_id: 1,
        },
        {
            id: 19,
            nom: "Intelligence Artificielle et Sciences des Données",
            faculty_id: 6,
            etablissement_id: 1,
        },
        {
            id: 20,
            nom: "Algèbre et Théorie des Nombres",
            faculty_id: 7,
            etablissement_id: 1,
        },
        {
            id: 21,
            nom: "Analyse",
            faculty_id: 7,
            etablissement_id: 1,
        },
        {
            id: 22,
            nom: "Probabilités et statistiques",
            faculty_id: 7,
            etablissement_id: 1,
        },
        {
            id: 23,
            nom: "Recherche opérationnelle",
            faculty_id: 7,
            etablissement_id: 1,
        },
        {
            id: 24,
            nom: "Physique des Rayonnements",
            faculty_id: 8,
            etablissement_id: 1,
        },
        {
            id: 25,
            nom: "Matériaux et Composant",
            faculty_id: 8,
            etablissement_id: 1,
        },
        {
            id: 26,
            nom: "Energétique et Mécanique des Fluides",
            faculty_id: 8,
            etablissement_id: 1,
        },
        {
            id: 27,
            nom: "Physique Théorique",
            faculty_id: 8,
            etablissement_id: 1,
        },
        {
            id: 28,
            nom: "Construction Mécanique et Productique",
            faculty_id: 9,
            etablissement_id: 1,
        },
        {
            id: 29,
            nom: "Thermo-Energétique",
            faculty_id: 9,
            etablissement_id: 1,
        },
        {
            id: 30,
            nom: "Science Des Matériaux",
            faculty_id: 9,
            etablissement_id: 1,
        },
        {
            id: 31,
            nom: "Génie Chimique et Cryogénie",
            faculty_id: 9,
            etablissement_id: 1,
        },
        {
            id: 32,
            nom: "Génie de l’Environnement",
            faculty_id: 9,
            etablissement_id: 1,
        },
    ]